WIDTH=1440
HEIGHT=720
GRID_SIZE=6
CELL_COUNT=GRID_SIZE ** 2
MINES_COUNT=(CELL_COUNT) // 4
FONT_TYPE='Arial'
BG_COLOR='black'
LETTER_COLOR='white'
CELL_COLOR='SystemButtonFace'
CELL_MINE='red'
CELL_CANDIDATE='orange'
GAME_TITLE='Minesweeper Game'
FINISH_TITLE='Game Over'
MSG_WIN='Congratulations! You win the game'
MSG_LOOSE='You click on a mine'
TXT_CELL_LEFT='Cells left:'